type ..\..\architecture\httpdlib\html\js\svg\jquery-1.7.1.min.js > jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\jquerysvg\jquery.svg.min.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\jquerysvg\jquery.svgdom.min.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_proto.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_jquery_svg_backend.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_mobile.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_ui_inits.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_load_external_file.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_ui_objects.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_ui_builder.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_ui_interact.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_ui_audio_bridge.js >> jsscripts
type empty.txt >> jsscripts
type ..\..\architecture\httpdlib\html\js\svg\faust_server_communication.js >> jsscripts
xxd -i jsscripts jsscripts.cpp
copy /Y jsscripts.cpp ..\..\architecture\httpdlib\src\hexa\jsscripts.cpp

type ..\..\architecture\httpdlib\html\js\svg\faust_css.css > stylesheet
xxd -i stylesheet stylesheet.cpp
copy /Y stylesheet.cpp ..\..\architecture\httpdlib\src\hexa\stylesheet.cpp
